#!/usr/bin/env bash

set -euo pipefail

# Script for installing dotfiles and make the pc confortable
# It can also be used to update the dotfiles

# git as requirement
if ! [ -x "$(command -v git)" ]; then
    echo "Install git"
    exit 1
fi

# Check if repositorie is cloning or it is updating
if [ -d ~/.local/git/dotfiles ] ; then
    git -C ~/.local/git/dotfiles/ pull
else
    mkdir -p ~/.config
    mkdir -p ~/.local/{bin,git}
    git clone https://github.com/ksobrenat32/dotfiles  ~/.local/git/dotfiles
    # Mark vim plugins as not active
    sed -i 's/Plug /"Plug/g' ~/.local/git/dotfiles/.vimrc
fi

# --- Create soft links
ln -fs ~/.local/git/dotfiles/.bash* ~
ln -fs ~/.local/git/dotfiles/.vimrc ~
ln -fs ~/.local/git/dotfiles/config/* ~/.config/
ln -fs ~/.local/git/dotfiles/bin/update ~/.local/bin/
