#!/usr/bin/env bash

set -e

# Script for installing dotfiles and make the pc confortable
# It can also be used to update the dotfiles

# Install git
if ! [ -x "$(command -v git)" ]; then
    if [ -x "$(command -v apt)" ]; then echo "Installing git" && sudo apt update -y && sudo apt install git -y
    elif [ -x "$(command -v dnf)" ]; then echo "Installing git" && sudo dnf install git -y
    else
        echo "Failed to identy package manager :(, Install git"
	exit 1
    fi
fi

# Check if repositorie is cloning or it is updating
if [ -d ~/.local/git/dotfiles ] ; then
    git -C ~/.local/git/dotfiles/ pull
else
    mkdir -p ~/.config
    mkdir -p ~/.local/{bin,git}
    git clone https://github.com/ksobrenat32/dotfiles  ~/.local/git/dotfiles
    sed -i 's/Plug /"Plug/g' ~/.local/git/dotfiles/.vimrc
fi

# --- Create soft links
# Scripts
ln -fs ~/.local/git/dotfiles/.bash* ~
ln -fs ~/.local/git/dotfiles/.profile ~
ln -fs ~/.local/git/dotfiles/.vimrc ~
ln -fs ~/.local/git/dotfiles/config/* ~/.config/
ln -fs ~/.local/git/dotfiles/bin/update* ~/.local/bin/
