#!/bin/sh

compressPDF(){
    gs -sDEVICE=pdfwrite \
        -dCompatibilityLevel=1.4 \
        -dPDFSETTINGS=/ebook \
        -dNOPAUSE \
        -dQUIET \
        -dBATCH \
        -sOutputFile="compressed.${1}" "${1}"
}

convertJPGPDF(){
    magick -density 300 -quality 100 "${1}" "${1}".pdf
}

fileBrowser(){
    docker run --rm \
        -v `pwd`/:/srv \
        -p 9000:80 \
        --security-opt label=disable \
        docker.io/filebrowser/filebrowser
}

