#!/bin/sh

# Add home bin path
if [ -d ~/.local/bin ]; then
    export PATH="$PATH:~/.local/bin"
fi

# Use vim as default editor
export SELECTED_EDITOR="/usr/bin/vim"
export EDITOR="/usr/bin/vim"

# Git GPG key
export GPG_TTY=$(tty)

# Disable less history
export LESSHISTFILE=-

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Source Aliases
if [ -f ~/.config/bash/aliases ]; then
	. ~/.config/bash/aliases
fi

# Source Functions
if [ -f ~/.config/bash/functions ]; then
	. ~/.config/bash/functions
fi

# Source custom scripts
for f in $(ls ~/.config/bash/*.bash)
do
    source $f
done
